### ISSUE TITLE
Example of save and read a value using the Bucket

### ISSUE THREAD

**Issue by vinicius-sabadim** [alinz/react-native-swiss-knife#1]
I have to congratulate you for this amazing work!

I lost almost one week trying to communicate my app and share extension. Thanks.
This is how I did.

On my app:
```javascript
import { RNSKBucket } from 'react-native-swiss-knife'
const myGroup = 'group.groupName'
RNSKBucket.set('test', 'myValue', myGroup)
```

On my extension:
```javascript
import { RNSKBucket } from 'react-native-swiss-knife'
const myGroup = 'group.groupName'
RNSKBucket.get('test', myGroup).then( (value) => console.log(value) ) // myValue
```

**Comment by alinz** [comment]
@vinicius-sabadim glad that it helps. Would you send me a PR and update the doc.

**Comment by rileytomasek** [comment]
@vinicius-sabadim @alinz this is super useful, but I'm not sure how to install it. I tried npm install and I'm getting an error. I assume that I need to link this somehow?

Any help would be greatly appreciated. Thanks :)

**Comment by alinz** [comment]
@RileyTomasek that is correct, you have to link the binary to your project. The linking part is always the same for all react-native projects. Have you linked any 3rd-party project with your react-native modules? if so, follow the same pattern.

**Comment by kristoff-it** [comment]
Hello I might have some trouble linking the library on android:

- Added the `include` and `projectDir` lines in `settings.gradle`
- Added the `compile` line under `dependencies` in `build.gradle`

I also reverted the manual changes I made and tried using `rnpm` to perform the linking but even after that I keep getting the same error when trying to read from the bucket.

The error that I get (from the share extension) is the following (which iirc is the same I had on iOS before linking):
```
ReactNativeJS: 'errrr', { [TypeError: undefined is not an object (evaluating 'RNSKBucket.get')]
```

And similarly I get the same error on the main app while writing in the bucket.

I should also note that the same code works perfectly on iOS after linking (exact same code, I have no ios/android distinction in my app for now) and that I'm using `react-native@0.38.0`.

Am I missing something?

**Comment by kristoff-it** [comment]
Well after a bit of tinkering I can answer myself: there are a couple of lines that need to be added to the java files about importing the library.

Great job with this lib, tank you!

**Comment by njt1982** [comment]
@kristoff-it what was your tinkering? I have the same issue with ios...

![image](https://user-images.githubusercontent.com/384976/27445982-c42b3676-5773-11e7-8c2c-c8cd661617d9.png)

![image](https://user-images.githubusercontent.com/384976/27446001-d43910f6-5773-11e7-9e5e-0d6386b0098a.png)

---

EDIT: I have run `react-native link`

---

This is how I am invoking it:

```
const onRequestSuccess = (response) => {
  if (response.status >= 200 && response.status < 300) {
    return response.json().then(function(tokens) {
      // Put the token info in the AppGroup Bucket
      RNSKBucket.set('tokens', JSON.stringify(tokens), USER_INFO_APP_GROUP_NAME);
```

---

So my group name and RNSKBucket are set in my app....

![image](https://user-images.githubusercontent.com/384976/27446295-f20b83b0-5774-11e7-9067-6252e88d884c.png)

**Comment by AbdelhalimAhmed** [comment]
@kristoff-it  can you tell me what's the couple of lines java should add ?
