### ISSUE TITLE
RNSKBucket not working

### ISSUE THREAD

**Issue by seclace** [alinz/react-native-swiss-knife#5]
Very useful library for communicating extension with app, but it seems to not working for me. I've installed and linked it such for extension as for app. It working separately for app and extension correctly, but getting the same key/value in extension that was set in the app is `null`. Similarly can't get the key/value in app that was set in extension. 

iOS simulator version `10.3`

    react-native --version
        react-native-cli: 2.0.1
        react-native: 0.42.3

from `package.json`:
```javascript
"react-native-share-extension": "^1.2.1",
"react-native-swiss-knife": "0.0.5",
```

EDIT: may be it using group apps, that it was worth noting? If so, it's not clear for me :)

EDIT 2: yes, it uses app groups for iOS and if I'll have some time I'll make PR for docs to clearify this.

**Comment by aayushanand99** [comment]
@seclace How did you solve this?!

**Comment by seclace** [comment]
@aayushanand99 as I wrote in "edit 2" - app needs to use app groups. You need to register app groups under your apple developer account and select this group in settings in your Xcode.
To get more info about how it works please see this topic [Sharing Data with Your Containing App](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW6)

**Comment by AbdelhalimAhmed** [comment]
i'm stuck on how can register app groups under apple developer account, can you clear it more ?
@seclace

**Comment by seclace** [comment]
@AbdelhalimAhmed yes. You should log in to your apple developer account on [official site](https://developer.apple.com)
Then go to 
![image](https://user-images.githubusercontent.com/13925962/35496636-6c8cf0ba-04f9-11e8-8073-7ac023a1f4dc.png)
Then go to 
![image](https://user-images.githubusercontent.com/13925962/35496676-a07269c8-04f9-11e8-9a2d-2ca1eebfb83d.png)
And press the `+` button in the right top of the groups view. Please, be more attentive.
